#!/usr/bin/env node
// launchkit — Reset Script
// Removes everything added by scripts/setup.js, restoring the base scaffold state.
// Run: node scripts/reset.js --project ../my-project

const fs = require("fs");
const path = require("path");
const { target, setTarget, parseProjectFlag, safeJsonParse, checkHelp } = require("./lib");

checkHelp(`
launchkit — Reset

  Removes everything added by setup.js, restoring the base scaffold state.

Usage:
  node scripts/reset.js [--project <path>]

Options:
  --project <path>    Path to the generated project (default: cwd)
  -h, --help          Show this help message

Examples:
  node scripts/reset.js --project ../my-site
`);

// ── Resolve target project ───────────────────────────────────────────────────
setTarget(parseProjectFlag());

// Everything setup.js copies into the project (on top of base scaffold)
const TO_REMOVE = [
  // app/ subdirectories (setup.js copies from templates/[type]/app/)
  // Base scaffold files (layout.tsx, globals.css, page.tsx, favicon.ico) are NOT touched
  "app/[locale]",
  "app/api",
  "app/components",
  "app/robots.ts",
  "app/sitemap.ts",
  "app/work",

  // Dictionaries (copied from templates/[type]/dictionaries/)
  "dictionaries",

  // Public assets (copied from templates/[type]/public/)
  "public/hero.jpg",
  "public/profile.jpg",
  "public/about.jpg",
  "public/og-image.png",
  "public/projects",

  // Dialogflow agent (portfolio only)
  "dialogflow",

  // i18n root files (copied from templates/[type]/root/ when i18n is enabled)
  "proxy.ts",
  "i18n-config.ts",
  "get-dictionary.ts",

  // Generated by setup.js
  ".env.example",
  ".launchkit",
];

// Optional deps added by setup.js based on feature selection
const OPTIONAL_DEPS = ["resend", "google-auth-library", "adm-zip"];

function removeOptionalDeps() {
  const pkgPath = path.join(target(), "package.json");
  if (!fs.existsSync(pkgPath)) return;
  const pkg = safeJsonParse(fs.readFileSync(pkgPath, "utf8"), "package.json");
  let changed = false;
  for (const dep of OPTIONAL_DEPS) {
    if (pkg.dependencies?.[dep]) { delete pkg.dependencies[dep]; changed = true; }
    if (pkg.devDependencies?.[dep]) { delete pkg.devDependencies[dep]; changed = true; }
  }
  if (changed) {
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
    console.log("  [restored] package.json — removed optional deps");
  }
}

let removed = 0;
for (const rel of TO_REMOVE) {
  const full = path.join(target(), rel);
  if (fs.existsSync(full)) {
    fs.rmSync(full, { recursive: true, force: true });
    console.log("  [removed]", rel);
    removed++;
  }
}

removeOptionalDeps();

if (removed === 0) {
  console.log("  Nothing to remove — project is already in base state.");
} else {
  console.log(`\n✓ Reset complete. ${removed} item(s) removed.`);
}
console.log("  Run setup.js --output to set up again.\n");
