#!/usr/bin/env node
// launchkit — Reset Script
// Removes everything added by scripts/setup.js, restoring the base template state.
// Run: node scripts/reset.js  (or: npm run reset)

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

// Everything setup.js copies into the project root
const TO_REMOVE = [
  // app/ subdirectories (setup.js copies from templates/[type]/app/)
  // Shared root files (layout.tsx, globals.css, page.tsx, favicon.ico) are NOT touched
  "app/[locale]",
  "app/api",
  "app/components",
  "app/robots.ts",
  "app/sitemap.ts",

  // Dictionaries (copied from templates/[type]/dictionaries/)
  "dictionaries",

  // Public assets (copied from templates/[type]/public/)
  "public/hero.jpg",
  "public/profile.jpg",
  "public/about.jpg",
  "public/og-image.png",
  "public/projects",

  // Dialogflow agent (portfolio only)
  "dialogflow",

  // i18n root files (copied from templates/[type]/root/ when i18n is enabled)
  "proxy.ts",
  "i18n-config.ts",
  "get-dictionary.ts",

  // Generated by setup.js
  ".env.example",
  ".launchkit",
];

// Optional deps added by setup.js based on feature selection
const OPTIONAL_DEPS = ["resend", "google-auth-library", "adm-zip"];

function removeOptionalDeps() {
  const pkgPath = path.join(ROOT, "package.json");
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  let changed = false;
  for (const dep of OPTIONAL_DEPS) {
    if (pkg.dependencies?.[dep]) { delete pkg.dependencies[dep]; changed = true; }
    if (pkg.devDependencies?.[dep]) { delete pkg.devDependencies[dep]; changed = true; }
  }
  if (changed) {
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
    console.log("  [restored] package.json — removed optional deps");
  }
}

let removed = 0;
for (const rel of TO_REMOVE) {
  const full = path.join(ROOT, rel);
  if (fs.existsSync(full)) {
    fs.rmSync(full, { recursive: true, force: true });
    console.log("  [removed]", rel);
    removed++;
  }
}

removeOptionalDeps();

if (removed === 0) {
  console.log("  Nothing to remove — project is already in base state.");
} else {
  console.log(`\n✓ Reset complete. ${removed} item(s) removed.`);
}
console.log("  Run node scripts/setup.js to set up again.\n");
